language: node_js 
node_js: 
- 15.0.1 
cache: yarn 

install: 
  - yarn install 
script: 
  - yarn test 
  - yarn run build 
deploy:
  provider: pages 
  cleanup: false
  github-token: $GITHUB_TOKEN
  local_dir: build
  on: 
    branch: gh-pages